# Generated by Django 4.2.4 on 2023-08-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='grade',
        ),
        migrations.AddField(
            model_name='class',
            name='title',
            field=models.CharField(choices=[('IT', 'IT'), ('SE', 'Software Engineering'), ('C', 'C')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
