# Generated by Django 4.2.4 on 2023-08-21 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0004_course_alter_class_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.class')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.course')),
                ('prf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
