# Generated by Django 4.2.4 on 2023-08-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_assignprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='isprofessor',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
