# Generated by Django 4.2.4 on 2023-08-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0006_isprofessor_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('Programming Fundamentals', 'Programming Fundamentals'), ('Islamic Studies', 'Islamic Studies')], max_length=100),
        ),
        migrations.CreateModel(
            name='Course_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='course_lectures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.course')),
            ],
        ),
    ]
