# Generated by Django 4.2.4 on 2023-09-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0011_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
