# Generated by Django 4.2.4 on 2023-09-11 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0013_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignprofessor',
            name='prf_id',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Professors'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
