# Generated by Django 4.2.4 on 2023-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0014_alter_assignprofessor_prf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='batch',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Software Engineering', 'Software Engineering'), ('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Engineering')], max_length=200),
        ),
    ]
