# Generated by Django 4.2.4 on 2023-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0015_alter_class_batch_alter_class_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Computer Engineering', 'Computer Engineering')], max_length=200),
        ),
    ]
