# Generated by Django 4.2.4 on 2023-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0016_alter_class_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
