# Generated by Django 4.2.4 on 2023-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0017_alter_class_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='course_title',
        ),
        migrations.RemoveField(
            model_name='class',
            name='title',
        ),
        migrations.AddField(
            model_name='class',
            name='class_title',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Software Engineering', 'Software Engineering'), ('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Engineering')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
